image:https://travis-ci.org/lookout/verspaetung.svg?branch=master["Build Status", link="https://travis-ci.org/lookout/verspaetung"]

image::https://api.bintray.com/packages/lookout/systems/verspaetung/images/download.svg[link="https://bintray.com/lookout/systems/verspaetung/_latestVersion"]

Versp채tung is a small utility which aims to help identify delay of link:http://kafka.apache.org[Kafka] consumers.


Versp채tung monitors the topics and their latest offsets by talking to Kafka, it
will also keep track of how far along consumers are by monitoring the offsets
that they have committed to Zookeeper. Using both of these pieces of
information, Versp채tung computs the delta for each of the consumer groups and
reports it to statsd.

=== Using

    % java -jar verspaetung-*-all.jar --help
    usage: verspaetung
     -H,--statsd-host <STATSD>   Hostname for a statsd instance (defaults to
                                 localhost)
     -n,--dry-run                Disable reporting to a statsd host
     -p,--statsd-port <PORT>     Port for the statsd instance (defaults to
                                 8125)
     -s,--storm                  Watch Storm KafkaSpout offsets (under
                                 /kafka_spout)
     -z,--zookeeper <HOSTS>      Comma separated list of Zookeeper hosts (e.g.
                                 localhost:2181)

Running Versp채tung is rather easy, by default the daemon will monitor the
standard Kafka high-level consumer offset path of `/consumers` and start
reporting deltas automatically.

